cinema/cinema/Controllers/ShowsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using cinema.Data;
using cinema.Models;
using cinema.Services;
using cinema.Filters;

namespace cinema.Controllers
{
    public class ShowsController : Controller
    {
        private readonly CinemaContext _context;
        private readonly ShowService _showService;

        public ShowsController(CinemaContext context, IShowService service)
        {
            
            _context = context;
            _showService = (ShowService) service;
        }

        // GET: Shows
        public async Task<IActionResult> Index()
        {
            
            var showList =  _context.Shows.Include(s => s.Movie).ToList();
            var showPerMoviePerDateDict = _showService.GetShowsPerMoviePerDay(showList);

            ShowsFilter filter = new ShowsFilter(showList);
            ViewData["ShowsFilter"] = filter;

            return View(showPerMoviePerDateDict);
        }

        // GET: Shows/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows
                .FirstOrDefaultAsync(m => m.Id == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // GET: Shows/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ThreeD,Room,StartTime,Break")] Show show)
        {
            if (ModelState.IsValid)
            {
                _context.Add(show);
                await _context.SaveChangesAsync();
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(show);
        }

        // GET: Shows/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows.FindAsync(id);
            if (show == null)
            {
                return NotFound();
            }
            return View(show);
        }

        // POST: Shows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ThreeD,Room,StartTime,Break")] Show show)
        {
            if (id != show.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(show);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShowExists(show.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(show);
        }

        // GET: Shows/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows
                .FirstOrDefaultAsync(m => m.Id == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // POST: Shows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var show = await _context.Shows.FindAsync(id);
            _context.Shows.Remove(show);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShowExists(int id)
        {
            return _context.Shows.Any(e => e.Id == id);
        }

        //GET: Shows/Daily
        public IActionResult Daily()
        {
            return View(_context.Shows.Include(s => s.Movie).Where(s => s.StartTime > DateTime.Now).Where(s => s.StartTime.Date == DateTime.Today.Date).ToList());
        }

        [HttpGet, HttpPost, ActionName("Filter")]
        public IActionResult Filter()
        {
            List<Show> shows = _context.Shows.Include(s => s.Movie).Where(s => s.StartTime > DateTime.Now).ToList();
            ShowsFilter filter = new ShowsFilter(shows);      
            if(Request.Method == HttpMethod.Post.Method)
            {
                if(Request.Form["search"] != "")
                    filter.input = Request.Form["search"];
                if (Request.Form["len"] != "")
                    filter.maxlength = Convert.ToDouble(Request.Form["len"]);
                if (Request.Form["date"] != "")
                    filter.date = Convert.ToDateTime(Request.Form["date"]);
                if (Request.Form["threed"] != "")
                    if (Request.Form["threed"] == "on")
                        filter.threed = true;
                    else
                        filter.threed = false;
                foreach (string language in filter.languages.Keys)
                    if (Request.Form[language] == "on")
                        filter.languages[language] = true;
                    else
                        filter.languages[language] = false;
                foreach (string genre in filter.genres.Keys)
                    if (Request.Form[genre] == "on")
                        filter.genres[genre] = true;
                    else
                        filter.genres[genre] = false;
                foreach (string kijkwijzer in filter.kijkwijzers.Keys)
                    if (Request.Form[kijkwijzer] == "on")
                        filter.kijkwijzers[kijkwijzer] = true;
                    else
                        filter.kijkwijzers[kijkwijzer] = false;
            }
            shows = filter.Apply(shows);
            ViewData["ShowsFilter"] = filter;
            return View("Index", _showService.GetShowsPerMoviePerDay(shows));
        }
    }
}

cinema/cinema/Controllers/SubscribersController.cs
using cinema.Data;
using cinema.Models;
using Microsoft.AspNetCore.Mvc;

namespace cinema.Controllers;

public class SubscribersController : Controller
{
    private readonly CinemaContext _context;

    public SubscribersController(CinemaContext context)
    {
        _context = context;
    }
    
    [HttpGet]
    [Route("/subscriber")]
    public IActionResult Index()
    {
        return View();
    }
    
    [HttpPost]
    [Route("/subscriber/create")]
    public IActionResult Create(
        [FromForm] string email)
    {
        Subscriber subscriber = new Subscriber();
        subscriber.Email = email;
        _context.Add(subscriber);
        _context.SaveChanges();
        return View(subscriber);
    }
}

cinema/cinema/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - cinema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    @await RenderSectionAsync("Styles", required: false)

</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand logo" href="#">
                <img src="~/imagesStyling/logo-se.png" alt="logo" class="img-responsive"/>
            </a>
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">cinema</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Shows" asp-action="Index">Voorstellingen</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
<div class="footer-container">
    <div id="mapssubscribe" class="container-fluid">
        <div class="row justify-content-evenly align-items-start">
            <div class="col-4">
                <input type="text" id="txtSource" placeholder="Vanaf"/>

                <input type="button" value="Route" onclick="GetRoute()" class="button button4"/>
                <div id="Dropdown">
                    <b>Ik kom: </b>
                    <select id="mode">
                        <option value="DRIVING">Met de auto</option>
                        <option value="WALKING">Lopend</option>
                        <option value="BICYCLING">Fietsend</option>
                        <option value="TRANSIT">Met de OV</option>
                    </select>
                </div>
                <hr/>
                <div id="dvDistance" style="font-weight:bold; text-align: center">
                </div>
                <div id="dvMap">
                </div>
                <div id="dvPanel">
                </div>
            </div>
            <div class="col-4">
                <div>
                    <h4>Aanmelden voor nieuwsbrief</h4>
                    <form method="post" asp-action="Create" asp-controller="Subscribers">
                        <input name="email" type="text" placeholder="Email adres">
                        <input type="submit" value="Aanmelden">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="border-top footer text-muted fixed-bottom">
    <div class="container footer-container">
        &copy; 2022 - cinema - <a asp-area="" asp-page="/Privacy">Privacy</a>
        <a class="social-media" href="https://www.facebook.com/avans/">
            <img src="~/imagesStyling/fb-bw.png" alt="fb" class="img-responsive"/>
        </a>
        <a class="social-media" href="https://www.instagram.com/avanshogeschool/?hl=en">
            <img src="~/imagesStyling/ig-bw.png" alt="ig" class="img-responsive"/>
        </a>
        <a class="social-media" href="https://twitter.com/avanshogeschool?lang=en">
            <img src="~/imagesStyling/tw-bw.png" alt="tw" class="img-responsive"/>
        </a>
    </div>
</footer>

<script src="~/lib/bootstrap/bootstrap.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCXagAu3PsqAZ2hW-1CA7HnMY0BjBF87GM&libraries=places">  
              </script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>